controllers/DashboardController.php
<?php


namespace app\controllers;


use app\components\MyHelpers;
use app\models\Organization;
use app\models\User;
use app\models\Work;
use yii\data\ActiveDataProvider;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\web\Controller;
use Yii;

class DashboardController extends Controller
{
    public $layout = 'master-login';
    public $array = [];
    /**
     * @param $token
     * @return string
     */


    public function actionIndex($organizationId){
        $organization = Organization::findOne(['id' => $organizationId]);
        $categories = Organization::find()->select('id,organizationName,parentId')->asArray()->all();
        $html_data = MyHelpers::showHtmlListData($organization,$categories);

        return $this->render('index',['data' => $html_data]);
    }

    public function showDashBoard($organizations, $parentId, $status)
    {
        $child = false;
        $query = (new Query())->SELECT([
            'w1.faOperationKind',
            'w1.start',
            'w1.end',
            'w1.createdAt',
            'w1.workedOrganizationId',
            'w1.status',
            'w1.id',
            'users.userName',
            'work_type.name nameWorkType',
            'up.*'
        ])
            ->FROM('work w1')
            ->INNERJOIN( 'users', 'w1.userCode = users.userCode')
            ->INNERJOIN('organization_parent up','w1.userCode = up.userCode')
            ->LEFTJOIN('self_check_task self', 'w1.id = self.workId')
            ->LEFTJOIN('work_type', 'self.workTypeId = work_type.id')
            ->WHERE('w1.id = (SELECT w2.id 
                    FROM work w2 
                    WHERE w2.userCode = w1.userCode AND w2.date = CURRENT_DATE 
                    ORDER BY w2.updatedAt DESC 
                    LIMIT 1)');
        if($status) {
            $query->andWhere(['w1.status' => $status]);
        } else {
            $query->andWhere('w1.status != 1 ')->andWhere('w1.status != 6');
        }
        $query->orderBy(['w1.createdAt' => SORT_DESC]);
        $listUserWork = $query->all();

        foreach ($organizations as $item)
        {
            if ($item['parentId'] == $parentId) {
                foreach ($listUserWork as $key => $work) {
                    if ($work['workedOrganizationId'] == $item['id']) {
                        $child = true;
                        if($work['status'] == 3) {
                            $this->array['waitting'][] = $work;

                        } else if($work['status'] == 2 || $work['status'] == 4){
                            $this->array['working'][] = $work;

                        } else if($work['status'] == 6) {
                            $this->array['finish'][] = $work;

                        } else if($work['status'] == 5) {
                            $this->array['decline'][] = $work;

                        }
                    }
                }
                if(!$child) {
                    $this->showDashBoard($organizations, $item['id'],$status);
                }
            }
        }
        if(!$child) {
            foreach ($listUserWork as $key => $work) {
                if ($parentId == $work['workedOrganizationId']) {
                    if($work['status'] == 3) {
                        $this->array['waitting'][] = $work;

                    } else if($work['status'] == 2 || $work['status'] == 4){
                        $this->array['working'][] = $work;

                    } else if($work['status'] == 6) {
                        $this->array['finish'][] = $work;

                    } else if($work['status'] == 5) {
                        $this->array['decline'][] = $work;
                    }

                }
            }
        }

        return $this->array;
    }

    public function actionDashboard($organizationId){
        //register
        $organization = Organization::findOne($organizationId);
        $categories = Organization::find()->select('id,organizationName,parentId')->asArray()->all();

        if(Yii::$app->request->isAjax){
                $getCheckbox  = Yii::$app->request->POST();
                $array_status = array();
                if ($getCheckbox['data']['cb-working'] == '1'){
                    $array_status[] = 2;
                    $array_status[] = 4;
                }
                if ($getCheckbox['data']['cb-confirm'] == '1'){
                    $array_status[] = 3;
                }
                if ($getCheckbox['data']['cb-decline'] == '1'){
                    $array_status[] = 5;
                }
                if ($getCheckbox['data']['cb-finished'] == '1'){
                    $array_status[] = 6;
                }
                if(count($array_status) > 0 )
                {
                    $data = $this->showDashBoard($categories, $organization['id'], $array_status);
                    return $this->renderAjax('table', ['data' => $data,'organization' => $organization,'categories'=>$categories]);
                }
                else
                {
                    $data = $this->showDashBoard($categories, $organization['id'], null);
                    return $this->renderAjax('table', ['data' => $data,'organization' => $organization,'categories'=>$categories]);
                }

        }else{
            $data = $this->showDashBoard($categories, $organization['id'], null);
            return $this->render('dashboard',['data' => $data,'organization' => $organization,'categories'=>$categories]);
        }
    }
}

controllers/WorkController.php
<?php


namespace app\controllers;


use app\models\Audio;
use app\models\ConfirmType;
use app\models\FilterForm;
use app\models\Image;
use app\models\Log;
use app\models\OfficeCheckTask;
use app\models\Organization;
use app\models\SelfCheckTask;
use app\models\User;
use app\models\Work;
use app\models\WorkType;
use Yii;
use yii\data\ActiveDataProvider;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\validators\ValidationAsset;
use yii\web\Controller;
use app\Constant\Constant;
use yii\web\Response;

class WorkController extends Controller
{
    public $layout = 'master-login';

    /**
     * @param $id
     * @return string
     */
    public function actionWorkDetail($id){
        $work = Work::findOne($id);
        if($work){
            $user = User::findByUserCode($work->userCode);
            $data = [
                'id' => $id,
                'userCode' => $work->userCode,
                'userName' => $user->userName,
                'phone' => $user->phone,
                'start' => $work->start,
                'end' => $work->end,
                'status' => $work->status,
                'officeComment' => $work->officeComment
            ];
            $data['checkType'] = $work->checkType;
            $office_task = OfficeCheckTask::findOne(['workId' => $id]);
            $self_task = SelfCheckTask::findOne(['workId' => $id]);
            $task = '';
            $data['images'] = [];
            if ($office_task) {
                $task = $office_task->id;
                $confirmTypeId = $office_task->confirmTypeId;
                $data['workContent'] = ConfirmType::findOne($confirmTypeId)->name;
            }
            if ($self_task) {
                $task = $self_task->id;
                $workTypeId = $self_task->workTypeId;
                $data['workContent'] = WorkType::findOne($workTypeId)->name;
            }
            if ($task) {
                $audio = Audio::findOne(['taskId' => $task]);
                $images = Image::findAll(['taskId' => $task]);
                if($audio){
                    $data['audio'] = $audio->fileName;
                }
                if (is_array($images)) {
                    foreach ($images as $image) {
                        $data['images'][] = $image->fileName;
                    }
                }
            }
            return $this->render('work-detail',['data' => $data]);
        }
    }


    /**
     * @param $id
     * @return bool
     */
    public function actionUpdateStatus($id){
        if(Yii::$app->request->isAjax){
            $data = Yii::$app->request->post('data','');
            $work = Work::findOne($id);
            $response = false;
            //update comment confirm
            if(isset($data['officeComment']) && $data['officeComment']){
                $work->officeComment = $data['officeComment'];
            }
            $status = (isset($data['isConfirm']) && $data['isConfirm'] === "1") ? 4 : 5;
            //update status
            $work->status = $status;
            if($work->save()){
                $response = true;
            }
            Yii::$app->response->format = Response::FORMAT_JSON;
            return $response;
        }
    }

    public function actionWorkList(){
        $model = new FilterForm();
        $organizationId = Yii::$app->user->identity->organizationId;
        $organizationLevel = $this->getOrganizationLevel($organizationId);
        $dataWorkList = $this->getWorkList($organizationId,$organizationLevel);
        foreach ($dataWorkList as $key => $item){
            $office_task = OfficeCheckTask::findOne(['workId' => $item['id']]);
            $self_task = SelfCheckTask::findOne(['workId' =>$item['id']]);
            $task = '';
            if ($office_task) {
                $task = $office_task->id;
            }
            if ($self_task) {
                $task = $self_task->id;
            }
            if ($task) {
                $images = Image::findAll(['taskId' => $task]);
                if (is_array($images)) {
                    foreach ($images as $image) {
                        $dataWorkList[$key]['images'][] = $image->fileName;
                    }
                }else{
                    $dataWorkList[$key]['images'][]='';
                }
            }
        }
        $workType = WorkType::find()->select(['name'])->asArray()->all();
        return $this->render('work-list',['dataWorkList' => $dataWorkList,'model'=>$model,'workType'=>$workType]);
    }

    private function getOrganizationLevel($organizationId){
        $organization = Organization::findOne($organizationId);
        $level = $organization->organizationLevelId;
        $key = '';
        switch ($level){
            case $level == 1:
                $key = 'level_id 1';
                break;
            case $level == 2:
                $key = 'level_id 2';
                break;
            case $level == 3:
                $key = 'level_id 3';
                break;
            case $level == 4:
                $key = 'level_id 4';
                break;
            case $level == 5:
                $key = 'level_id 5';
                break;
        }
        return $key;
    }
    public function getWorkList($organizationId, $organizationLevel)
    {
        $query = (new Query())->SELECT([
            'w1.faOperationKind',
            'w1.start',
            'w1.end',
            'w1.createdAt',
            'w1.workedOrganizationId',
            'w1.status',
            'w1.id id',
            'w1.date',
            'w1.officeComment',
            'users.userName',
            'work_type.name nameWorkType',
            'confirm_type.name nameConfirmType',
            'audio.fileName as audioName',
            'confirm_type.aerialWork as officeArialWork',
            'work_type.aerialWork as selfArialWork',
            'op.*'

        ])
            ->FROM('work w1')
            ->INNERJOIN('users', 'w1.userCode = users.userCode')
            ->INNERJOIN('organization_parent op', 'w1.userCode = op.userCode')
            ->LEFTJOIN('self_check_task self', 'w1.id = self.workId')
            ->LEFTJOIN('work_type', 'self.workTypeId = work_type.id')
            ->LEFTJOIN('office_check_task office', 'w1.id = office.workId')
            ->LEFTJOIN('confirm_type', 'office.confirmTypeId = confirm_type.id')
            ->leftJoin('audio','(audio.taskId = office.id and audio.checkType = w1.checkType) 
                        or (audio.taskId = self.id and audio.checkType = w1.checkType )')
            ->WHERE('w1.id = (SELECT w2.id 
                    FROM work w2 
                    WHERE w2.userCode = w1.userCode 
                    ORDER BY w2.updatedAt DESC 
                    LIMIT 1)')
            ->andWhere('w1.status != 1')
            ->andWhere('w1.status != 6')
            ->andWhere([$organizationLevel => $organizationId])
            ->orderBy(['w1.createdAt' => SORT_DESC]);
        return $query->all();
    }




}

views/dashboard/dashboard.php
<?php
use yii\grid\GridView;
use yii\widgets\Pjax;
use app\components\MyHelpers;
/** @var \yii\data\ActiveDataProvider $dataProvider */
/** @var  array $information */
/** @var int $id */

?>
<div class="info-filter">
    <div id="organization-info">
        <div class="info">
            <div class="info-name"><?= Yii::t('app','Register')?></div>
            <div class="value">
                <?=
                /** @var array $organization */
                $organization['numberOfUsers'];
                ?>
            </div>
        </div>
        <div class="info">
            <div class="info-name"><?= Yii::t('app','Working')?></div>
            <div class="value">
                <?=
                /** @var array $categories */
                MyHelpers::getWorkingTotal($categories,$organization['id'])
                ?>
            </div>
        </div>
        <div class="info">
            <div class="info-name"><?= Yii::t('app','Wait for confirm')?></div>
            <div class="value">
                <?=
                /** @var array $categories */
                MyHelpers::getWaitListTotal($categories,$organization['id']);
                ?>
            </div>
        </div>
    </div>
    <div id="organization-filter">
        <label class="checkbox-inline"><input type="checkbox" id="cb-working" class="checkbox-group" name="cb-working"><?= Yii::t('app','Working')?></label>
        <label class="checkbox-inline"><input type="checkbox" id="cb-confirm" class="checkbox-group" name="cb-confirm"><?= Yii::t('app','Waiting confirm')?></label>
        <label class="checkbox-inline"><input type="checkbox" id="cb-decline" class="checkbox-group" name="cb-decline"><?= Yii::t('app','Decline')?></label>
        <label class="checkbox-inline"><input type="checkbox" id="cb-finished" class="checkbox-group" name="cb-finished"><?= Yii::t('app','Finished')?></label>
        <a href="" onClick="document.location.reload(true)">
            <span class="glyphicon glyphicon-refresh pull-right" style="font-size: 30px; margin-right: 5px;"></span>
        </a>
    </div>
</div>
<table class="table table-bordered">
    <thead>
    <tr>
        <td>支店</td>
        <td>営業所</td>
        <td>FSC</td>
        <td>拠点</td>
        <td>社員名</td>
        <td>案件種別</td>
        <td>作業内容</td>
        <td>開始</td>
        <td>経過時間</td>
        <td>完了時刻</td>
    </tr>
    </thead>
    <tbody id="tb_dashboard_t">
        <?php
            echo $this->render('table',['data' => $data,'organization' => $organization,'categories'=>$categories]);
        ?>
    </tbody>
</table>




<script>
    var urlEditCheckbox = "<?= \yii\helpers\Url::to(['dashboard/dashboard'])?>";
    var organizationId = "<?= $organization['id'] ?>";
    function autoRefreshPage()
    {
        window.location = window.location.href;
    }
    setInterval('autoRefreshPage()', 180000);


</script>
<?php $this->registerCssFile('@web/css/dash-board.css')?>
<?php $this->registerJsFile('@web/js/dash-board.js',['depends' => [\yii\web\JqueryAsset::className()]]);?>

views/dashboard/index.php
<?php
/** @var yii\web\View\ $this */
use yii\web\View;
$this->title = Yii::t('app','Confirm Work');
?>
<div class="container-fluid" style="width:80%; margin-top: 30px">
    <div class="header">
        <div id="first-item"><?= Yii::t('app','Company')?></div>
        <div class="item-value"> <?= Yii::t('app','Wait for confirm')?></div>
        <div class="item-value"> <?= Yii::t('app','Working')?></div>
        <div class="item-value"> <?= Yii::t('app','Register')?></div>
    </div>
    <div class="items">
        <?= $data ;?>
    </div>

</div>


<?php $this->registerCssFile('@web/css/table.css')?>

views/dashboard/table.php
<?php
use yii\helpers\Url;
/** @var id $organizationId */
?>

<?php



if (isset($data['waitting'])) {
    foreach ($data['waitting'] as $row) {

        $url = Url::to(['work/work-detail','id' => $row['id']]);
        ?>
        <tr style="background-color: deeppink" class="row-waitting" onclick="window.location.href = '<?= $url ?>'">
            <td> <?= $row['level_name 2'] ?> </td>
            <td> <?= $row['level_name 3'] ?> </td>
            <td> <?= $row['level_name 4'] ?> </td>
            <td> <?= $row['level_name 5'] ?> </td>
            <td> <?= $row['userName'] ?> </td>
            <td> <?= $row['faOperationKind'] ?> </td>
            <td> <?= $row['nameWorkType'] ?> </td>
            <?php
            date_default_timezone_set("Asia/Bangkok");
            $start = strtotime($row['start']);
            $timestamp = time();
            $hours_tinh =  $timestamp - $start;
            $hours = floor($hours_tinh / 3600);
            $minutes = floor(($hours_tinh / 60) % 60);
            ?>
            <td> <?= date('H:i',$start) ?> </td>
            <?php
                if ($start < 0){
                ?>
                    <td></td>
            <?php }else{ ?>
                    <td><?= "$hours:$minutes"?></td>
            <?php } ?>
            <td> <?= $row['end'] ?> </td>
        </tr>
        <?php
    }
}

if (isset($data['working'])) {
    foreach ($data['working'] as $row) {
        $url = Url::to(['work/work-detail','id' => $row['id']]);
        ?>
        <tr style="background-color: #0a73bb" class="row-waitting" onclick="window.location.href = '<?= $url ?>'">
            <td> <?= $row['level_name 2'] ?> </td>
            <td> <?= $row['level_name 3'] ?> </td>
            <td> <?= $row['level_name 4'] ?> </td>
            <td> <?= $row['level_name 5'] ?> </td>
            <td> <?= $row['userName'] ?> </td>
            <td> <?= $row['faOperationKind'] ?> </td>
            <td> <?= $row['nameWorkType'] ?> </td>
            <?php
            date_default_timezone_set("Asia/Bangkok");
            $start = strtotime($row['start']);
            $timestamp = time();
            $hours_tinh =  $timestamp - $start;
            $hours = floor($hours_tinh / 3600);
            $minutes = floor(($hours_tinh / 60) % 60);
            ?>
            <td> <?= date('H:i',$start) ?> </td>
            <?php
            if ($start < 0){
                ?>
                <td></td>
            <?php }else{ ?>
                <td><?= "$hours:$minutes"?></td>
            <?php } ?>
            <td> <?= $row['end'] ?> </td>
        </tr>
        <?php
    }
}

if (isset($data['decline'])) {
    foreach ($data['decline'] as $row) {
        $url = Url::to(['work/work-detail','id' => $row['id']]);
        ?>
        <tr class="row-waitting" onclick="window.location.href = '<?= $url ?>'">
            <td> <?= $row['level_name 2'] ?> </td>
            <td> <?= $row['level_name 3'] ?> </td>
            <td> <?= $row['level_name 4'] ?> </td>
            <td> <?= $row['level_name 5'] ?> </td>
            <td> <?= $row['userName'] ?> </td>
            <td> <?= $row['faOperationKind'] ?> </td>
            <td> <?= $row['nameWorkType'] ?> </td>
            <?php
            date_default_timezone_set("Asia/Bangkok");
            $start = strtotime($row['start']);
            $timestamp = time();
            $hours_tinh =  $timestamp - $start;
            $hours = floor($hours_tinh / 3600);
            $minutes = floor(($hours_tinh / 60) % 60);
            ?>
            <td> <?= date('H:i',$start) ?> </td>
            <?php
            if ($start < 0){
                ?>
                <td></td>
            <?php }else{ ?>
                <td><?= "$hours:$minutes"?></td>
            <?php } ?>
            <td> <?= $row['end'] ?> </td>
        </tr>
        <?php
    }
}

if (isset($data['finish'])) {
    foreach ($data['finish'] as $row) {
        $url = Url::to(['work/work-detail','id' => $row['id']]);
        ?>
        <tr style="background-color: grey" class="row-waitting" onclick="window.location.href = '<?= $url ?>'">
            <td> <?= $row['level_name 2'] ?> </td>
            <td> <?= $row['level_name 3'] ?> </td>
            <td> <?= $row['level_name 4'] ?> </td>
            <td> <?= $row['level_name 5'] ?> </td>
            <td> <?= $row['userName'] ?> </td>
            <td> <?= $row['faOperationKind'] ?> </td>
            <td> <?= $row['nameWorkType'] ?> </td>
            <?php
            date_default_timezone_set("Asia/Bangkok");
            $start = strtotime($row['start']);
            $timestamp = time();
            $hours_tinh =  $timestamp - $start;
            $hours = floor($hours_tinh / 3600);
            $minutes = floor(($hours_tinh / 60) % 60);
            ?>
            <td> <?= date('H:i',$start) ?> </td>
            <?php
            if ($start < 0){
                ?>
                <td></td>
            <?php }else{ ?>
                <td><?= "$hours:$minutes"?></td>
            <?php } ?>
            <td> <?= $row['end'] ?> </td>
        </tr>
        <?php
    }
}

?>