models/Work.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

/**
 * This is the model class for table "work".
 *
 * @property int $id
 * @property string $userCode
 * @property int $workedOrganizationId
 * @property string $code
 * @property string $officeComment
 * @property int $status
 * @property string $start
 * @property string $end
 * @property int $checkType
 * @property string $date
 * @property string $powerAIImage
 * @property int $confirmStatus
 * @property int $isObjectRecognizeSuccess
 * @property string $faOperationId
 * @property string $faOperationKind
 * @property string $faOperationDetail
 * @property string $faOperationDate
 * @property string $faConstructionTimePeriod
 * @property string $createdAt
 * @property string $updatedAt
 */
class Work extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'work';
    }

    /**
     * {@inheritdoc}
     */

    public function rules()
    {
        return [
            [['userCode', 'workedOrganizationId','date'], 'required'],
            [['workedOrganizationId', 'status', 'checkType', 'confirmStatus', 'isObjectRecognizeSuccess'], 'integer'],
            [['start', 'end', 'date'], 'safe'],
            [['userCode', 'code'], 'string', 'max' => 45],
            [['officeComment'], 'string', 'max' => 300],
            [['powerAIImage'], 'string', 'max' => 255],
            [['faOperationId', 'faOperationKind', 'faOperationDate', 'faConstructionTimePeriod'], 'string', 'max' => 30],
            [['faOperationDetail'], 'string', 'max' => 100],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'userCode' => 'User Code',
            'workedOrganizationId' => 'Worked Organization ID',
            'code' => 'Code',
            'officeComment' => 'Office Comment',
            'status' => 'Status',
            'start' => 'Start',
            'end' => 'End',
            'checkType' => 'Check Type',
            'date' => 'Date',
            'powerAIImage' => 'Power AI Image',
            'confirmStatus' => 'Confirm Status',
            'isObjectRecognizeSuccess' => 'Is Object Recognize Success',
            'faOperationId' => 'Fa Operation ID',
            'faOperationKind' => 'Fa Operation Kind',
            'faOperationDetail' => 'Fa Operation Detail',
            'faOperationDate' => 'Fa Operation Date',
            'faConstructionTimePeriod' => 'Fa Construction Time Period',
            'createdAt' => 'Created At',
            'updatedAt' => 'Updated At',
        ];
    }

    /*public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'createdAt',
                'updatedAtAttribute' => 'updatedAt',
                'value' => new Expression('NOW()'),
            ],
        ];
    }*/
}

models/WorkType.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "work_type".
 *
 * @property int|null $id
 * @property string|null $name
 * @property int|null $aerialWork
 * @property string|null $scene
 * @property string|null $createdAt
 * @property string|null $updatedAt
 * @property int|null $displayOrder
 */
class WorkType extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'work_type';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id', 'aerialWork', 'displayOrder'], 'integer'],
            [['name'], 'string', 'max' => 8],
            [['scene'], 'string', 'max' => 17],
            [['createdAt', 'updatedAt'], 'string', 'max' => 26],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'aerialWork' => 'Aerial Work',
            'scene' => 'Scene',
            'createdAt' => 'Created At',
            'updatedAt' => 'Updated At',
            'displayOrder' => 'Display Order',
        ];
    }
}

controllers/WorkController.php
<?php


namespace app\controllers;


use app\models\Audio;
use app\models\ConfirmType;
use app\models\FilterForm;
use app\models\Image;
use app\models\Log;
use app\models\OfficeCheckTask;
use app\models\Organization;
use app\models\SelfCheckTask;
use app\models\User;
use app\models\Work;
use app\models\WorkType;
use Yii;
use yii\data\ActiveDataProvider;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\validators\ValidationAsset;
use yii\web\Controller;
use app\Constant\Constant;
use yii\web\Response;

class WorkController extends Controller
{
    public $layout = 'master-login';

    /**
     * @param $id
     * @return string
     */
    public function actionWorkDetail($id){
        $work = Work::findOne($id);
        if($work){
            $user = User::findByUserCode($work->userCode);
            $data = [
                'id' => $id,
                'userCode' => $work->userCode,
                'userName' => $user->userName,
                'phone' => $user->phone,
                'start' => $work->start,
                'end' => $work->end,
                'status' => $work->status,
                'officeComment' => $work->officeComment
            ];
            $data['checkType'] = $work->checkType;
            $office_task = OfficeCheckTask::findOne(['workId' => $id]);
            $self_task = SelfCheckTask::findOne(['workId' => $id]);
            $task = '';
            $data['images'] = [];
            if ($office_task) {
                $task = $office_task->id;
                $confirmTypeId = $office_task->confirmTypeId;
                $data['workContent'] = ConfirmType::findOne($confirmTypeId)->name;
            }
            if ($self_task) {
                $task = $self_task->id;
                $workTypeId = $self_task->workTypeId;
                $data['workContent'] = WorkType::findOne($workTypeId)->name;
            }
            if ($task) {
                $audio = Audio::findOne(['taskId' => $task]);
                $images = Image::findAll(['taskId' => $task]);
                if($audio){
                    $data['audio'] = $audio->fileName;
                }
                if (is_array($images)) {
                    foreach ($images as $image) {
                        $data['images'][] = $image->fileName;
                    }
                }
            }
            return $this->render('work-detail',['data' => $data]);
        }
    }


    /**
     * @param $id
     * @return bool
     */
    public function actionUpdateStatus($id){
        if(Yii::$app->request->isAjax){
            $data = Yii::$app->request->post('data','');
            $work = Work::findOne($id);
            $response = false;
            //update comment confirm
            if(isset($data['officeComment']) && $data['officeComment']){
                $work->officeComment = $data['officeComment'];
            }
            $status = (isset($data['isConfirm']) && $data['isConfirm'] === "1") ? 4 : 5;
            //update status
            $work->status = $status;
            if($work->save()){
                $response = true;
            }
            Yii::$app->response->format = Response::FORMAT_JSON;
            return $response;
        }
    }

    public function actionWorkList(){
        $model = new FilterForm();
        $organizationId = Yii::$app->user->identity->organizationId;
        $organizationLevel = $this->getOrganizationLevel($organizationId);
        $dataWorkList = $this->getWorkList($organizationId,$organizationLevel);
        foreach ($dataWorkList as $key => $item){
            $office_task = OfficeCheckTask::findOne(['workId' => $item['id']]);
            $self_task = SelfCheckTask::findOne(['workId' =>$item['id']]);
            $task = '';
            if ($office_task) {
                $task = $office_task->id;
            }
            if ($self_task) {
                $task = $self_task->id;
            }
            if ($task) {
                $images = Image::findAll(['taskId' => $task]);
                if (is_array($images)) {
                    foreach ($images as $image) {
                        $dataWorkList[$key]['images'][] = $image->fileName;
                    }
                }else{
                    $dataWorkList[$key]['images'][]='';
                }
            }
        }
        $workType = WorkType::find()->select(['name'])->asArray()->all();
        return $this->render('work-list',['dataWorkList' => $dataWorkList,'model'=>$model,'workType'=>$workType]);
    }

    private function getOrganizationLevel($organizationId){
        $organization = Organization::findOne($organizationId);
        $level = $organization->organizationLevelId;
        $key = '';
        switch ($level){
            case $level == 1:
                $key = 'level_id 1';
                break;
            case $level == 2:
                $key = 'level_id 2';
                break;
            case $level == 3:
                $key = 'level_id 3';
                break;
            case $level == 4:
                $key = 'level_id 4';
                break;
            case $level == 5:
                $key = 'level_id 5';
                break;
        }
        return $key;
    }
    public function getWorkList($organizationId, $organizationLevel)
    {
        $query = (new Query())->SELECT([
            'w1.faOperationKind',
            'w1.start',
            'w1.end',
            'w1.createdAt',
            'w1.workedOrganizationId',
            'w1.status',
            'w1.id id',
            'w1.date',
            'w1.officeComment',
            'users.userName',
            'work_type.name nameWorkType',
            'confirm_type.name nameConfirmType',
            'audio.fileName as audioName',
            'confirm_type.aerialWork as officeArialWork',
            'work_type.aerialWork as selfArialWork',
            'op.*'

        ])
            ->FROM('work w1')
            ->INNERJOIN('users', 'w1.userCode = users.userCode')
            ->INNERJOIN('organization_parent op', 'w1.userCode = op.userCode')
            ->LEFTJOIN('self_check_task self', 'w1.id = self.workId')
            ->LEFTJOIN('work_type', 'self.workTypeId = work_type.id')
            ->LEFTJOIN('office_check_task office', 'w1.id = office.workId')
            ->LEFTJOIN('confirm_type', 'office.confirmTypeId = confirm_type.id')
            ->leftJoin('audio','(audio.taskId = office.id and audio.checkType = w1.checkType) 
                        or (audio.taskId = self.id and audio.checkType = w1.checkType )')
            ->WHERE('w1.id = (SELECT w2.id 
                    FROM work w2 
                    WHERE w2.userCode = w1.userCode 
                    ORDER BY w2.updatedAt DESC 
                    LIMIT 1)')
            ->andWhere('w1.status != 1')
            ->andWhere('w1.status != 6')
            ->andWhere([$organizationLevel => $organizationId])
            ->orderBy(['w1.createdAt' => SORT_DESC]);
        return $query->all();
    }




}

views/work/work-detail.php
<?php

use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\helpers\Url;
use app\models\User;
/** @var array $data */
$disabled = true;

if($data['audio']){
    $disabled = false;
}
$isConfirmWork = false;
$permission = User::CanConfirmWorkDetail(Yii::$app->user->identity->getId());
$workStatus = [2,3];
if(in_array($data['status'],$workStatus) && $permission){
    $isConfirmWork = true;
}


?>
<div class="row" id="user-work-info">
    <div class="col-md-4" >
        <p>User code: <?= $data['userCode'] ?></p>
        <p>User name: <?= $data['userName'] ?> </p>
        <p>Phone number: <?= $data['phone'] ?> </p>
    </div>
    <div class="col-md-4">
        <p class="info-label">Start time</p>
        <p><?= $data['start']?></p>
        <p class="info-label">Work content</p>
        <p><?= $data['workContent'] ?></p>
    </div>
    <div class="col-md-4">
        <p class="info-label">End time</p>
        <p><?= $data['end'] ?></p>
    </div>
</div>

<div id="work-image">
    <p>Work Detail Image</p>
    <div class="row" id="image">
        <?php foreach ($data['images'] as $image){?>
            <div class="col-md-4 col-image">
                <h4>チェック項目</h4>
                <div class="row">
                    <div class="col-md-7" style="height: 300px">
                        <div class="class_confirm">
                            <i class='fas fa-check' style='color:white'></i>
                            確認内容レコメンド
                        </div>
                    </div>
                    <div class="col-md-5 image-right">
                        <img src=<?= '/basic/upload/'.DIRECTORY_SEPARATOR.$image ?> alt="Image" class="img-responsive" style="height: 300px">

                    </div>
                </div>

            </div>
        <?php }?>
    </div>

    <div class="row">
        <div id="user-comment">
            <p><?= $data['audio']  ?></p>
        </div>
        <div id="confirm-audio-button">
            <?= Html::button(Yii::t('app','Confirm Audio'),['id' => 'confirm-audio','class' => 'btn btn-primary','disabled' => $disabled])?>
        </div>
    </div>
    <div class="row">
        <label><?= Yii::t('app','Confirm comment')?></label>
        <br >
        <input type="text" class="form-control" id="confirm-comment" value="<?= $data['officeComment'] ?>" maxlength="300">
        <div id="button-detail">
            <?= Html::button(Yii::t('app','Decline'),['id' => 'btn-decline','class' => 'btn btn-danger'])?>
            <?= Html::button(Yii::t('app','Accept'),['id' => 'btn-accept','class' => 'btn btn-primary'])?>
        </div>

    </div>
    <div>
        <audio id ="audio-file">
            <?php if($data['audio']) {?>
                <source src=<?= '/basic/upload/'.DIRECTORY_SEPARATOR.$data['audio'] ?> type="audio/mp3">
                Your browser does not support the audio element.
            <?php } ?>
        </audio>
    </div>

</div>

<!--Modal confirm M31-->
<?php
Modal::begin([
    'id' => 'modal-confirm',
    'closeButton' => false,
]);
?>
<div id="confirm-message" style="font-size: 20px; margin-bottom: 15px;">
    <p>確認で送信しますか？</p>
</div>
<div id="btn-group">
    <button class="btn btn-primary" id='btn-confirm'> 確認</button>
    <button class="btn btn-danger" id='btn-not-confirm'>否認</button>
</div>
<?php Modal::end(); ?>

<!--Modal decline M30-->
<?php
Modal::begin([
    'id' => 'modal-decline',
    'closeButton' => false,
]);
?>
<div id="confirm-message" style="font-size: 20px; margin-bottom: 15px;">
    <p>否認で送信しますか？</p>
</div>
<div id="btn-group">
    <button class="btn btn-primary" id='btn-yes'> 確認</button>
    <button class="btn btn-danger" id='btn-no'>否認</button>
</div>
<?php Modal::end(); ?>

<!--modal image-->
<?php
Modal::begin([
    'id' => 'modal-image',
    'closeButton' => false,
    'size' => 'modal-dialog'
]);
?>
<img class="image_modal" src="" alt="" style="width: 100%;height: 100%">
<?php Modal::end(); ?>
<!--end modal image-->


<script>
    var csrf = "<?=Yii::$app->request->getCsrfToken()?>";
    var urlUpdateStatusWork = "<?= \yii\helpers\Url::to(['work/update-status','id' => $_GET['id']])?>";
    var isConfirmWorkDetail = "<?php echo $isConfirmWork ?>" ;
</script>



<?php $this->registerCssFile('@web/css/work-detail.css') ?>
<?php $this->registerJsFile('@web/js/work-detail.js',['depends' => [\yii\web\JqueryAsset::className()]]) ?>

views/work/work-list.php
<?php
use yii\helpers\Url;
use yii\bootstrap\Modal;
use kartik\date\DatePicker;
use yii\bootstrap\ActiveForm;

$identify = [
    0 => 'Short place',
    1 => 'High place',
];

?>

<div>
    <div class="row" style="margin-bottom: 10px;">
        <div class="col-md-6">
            <button class="btn btn-default btn-event" id="btn-filter"><?= Yii::t('app', 'Filter')?></button>
            <button class="btn btn-default btn-event" id="btn-clear"><?= Yii::t('app', 'Clear')?></button>
        </div>
    </div>
    <table class="table table-bordered" style="text-align: center;">
        <thead>
        <tr class="header-table">
            <th rowspan="2">DL</th>
            <th rowspan="2">WorkId</th>
            <th rowspan="2">Finish time</th>
            <th rowspan="2">Operation Kind</th>
            <th rowspan="2">Identify the high place</th>
            <th colspan="4">Organization</th>
            <th rowspan="2">Seri ID</th>
            <th rowspan="2">Date</th>
            <th rowspan="2">Work Content</th>
            <th colspan="4">Picture</th>
            <th rowspan="2">Audio</th>
            <th rowspan="2">KY division</th>
            <th rowspan="2">Result</th>
        </tr>
        <tr class="header-table">
            <th>Branch/Office</th>
            <th>FSC/Facility</th>
            <th>Employee</th>
            <th>Working employee</th>
            <th>Picture 1</th>
            <th>Picture 2</th>
            <th>Picture 3</th>
            <th>#</th>
        </tr>
        </thead>
        <tbody>
            <?php
            /** @var array $dataWorkList */
            foreach ($dataWorkList as $row){

            ?>
                <tr>
                    <td><input type="checkbox" class="cb-download" name="cb-download-<?= $row['id'] ?>" value="<?= $row['id'] ?>"></td>
                    <td><?= $row['id'] ?></td>
                    <td><?= $row['end'] ?></td>
                    <td><?= $row['faOperationKind'] ?></td>
                    <td>
                       <?php
                        $value = '';
                        if($data = $row['officeArialWork'] || $data = $row['selfArialWork']){
                            $value = $data == 1 ? 'High place': 'Short place';
                        }
                        echo $value;
                        ?>
                    </td>
                    <td><?= $row['level_name 2'].'-'.$row['level_name 3'] ?></td>
                    <td><?= $row['level_name 4'] ?></td>
                    <td></td>
                    <td><?= $row['userName'] ?></td>
                    <td><a href="<?= Url::to(['work/work-detail','id' => $row['id']])?>"><?= $row['faOperationKind'].'-'.$row['start'].'-'.$row['id'] ?></a></td>
                    <td><?php
                        $value = $row['date'];
                        if($row['start']){
                            $value .= '-'.$row['start'];
                        }
                        echo $value;
                        ?>
                    </td>
                    <td><?php
                        $value = '';
                        if ($row['nameConfirmType']) {
                            $value = $row['nameConfirmType'];
                        }
                        if ($row['nameWorkType']) {
                            $value = $row['nameWorkType'];
                        }
                        echo $value;
                        ?>
                    </td>

                        <?php
                        if (isset($row['images'])){
                            $count = 0;
                            foreach ($row['images'] as $key => $image){
                                $count++;
                               if ($key == 3){
                                   break;
                               }
                        ?>
                                <td>
                                    <img src=<?= '/basic/upload/'.DIRECTORY_SEPARATOR.$image ?> alt="Image" class="img-responsive" style="height: 80px">
                                </td>
                            <?php }
                            if($count < 3)
                            {
                                for($i = $count ; $i < 3 ; $i++)
                                {
                                    ?>
                                    <td>
                                    </td>
                                    <?php
                                }
                            }
                            ?>
                        <?php } else {
                            echo '<td></td><td></td><td></td>';
                        } ?>

                    <td>
                        <?php
                            if(is_array(isset($row['images'])) && count(isset($row['images']) > 3)){
                                echo '有';
                            }else{
                                echo '無';
                            }
                        ?>
                    </td>
                    <!-- $row['audioName']-->
                    <td style="color:lightskyblue;text-decoration: underline;" id="td-audio">
                        <?php if($row['audioName']) {?>
                        <p id ="confirm-audio" style="cursor: pointer;">Play</p>
                        <audio id ="audio-file">
                                <source src=<?= '/basic/upload/'.DIRECTORY_SEPARATOR.$row['audioName'] ?> type="audio/mp3">
                                Your browser does not support the audio element.
                        </audio>
                        <?php } ?>
                    </td>


                    <td></td>
                    <td>
                        <?php
                            $value = '';
                            switch ($row['status']){
                                case 4:
                                    if($row['officeComment']){
                                        $value = 'コメント有り';
                                    }else{
                                        $value = '確認済';
                                    }
                                    break;
                                case 5:
                                    $value = '不備有り';
                                    break;
                            }
                            echo $value;
                        ?>
                    </td>
                </tr>


            <?php
            }
            ?>

        </tbody>
    </table>
</div>
<!--Filter modal-->
<?php
Modal::begin([
    'header' =>  Yii::t('app','Filter'),
    'id' => 'filter',
    'closeButton' => false,
    'size' => 'modal-lg'
]);
?>
<?php $form = ActiveForm::begin(
    [
        'id' => 'filter-search-form',
        'fieldConfig' => [
            'enableError' => false,
        ],
    ]
)
?>
<div style="text-align: center">
    <div class="form-inline">
        <div class="form-group filter-form" >
            <?= $form->field($model,'startDate')->Widget(
                DatePicker::className(),
                [
                    'name' => 'startDate',
                    'value' => Date('Y-m-d'),
                    'type' => DatePicker::TYPE_COMPONENT_PREPEND,
//                    'removeButton' => false,
                    'pluginOptions' => [
                        'autoclose' => true,
                        'format' => 'yyyy-mm-dd'
                    ]
                ]
            )->label(Yii::t('app','Date'))?>
        </div>
        <div class="form-group filter-form">
            <?= $form->field($model,'endDate')->widget(
                DatePicker::className(),
                ['name' => 'endDate',
                    'value' => Date('Y-m-d'),
                    'type' => DatePicker::TYPE_COMPONENT_PREPEND,
//                    'removeButton' => false,
                    'pluginOptions' => [
                        'autoclose' => true,
                        'format' => 'yyyy-mm-dd'
                    ]
                ]
            )->label('~')?>
        </div>
    </div>

    <div class="form-inline">
        <div class="form-group filter-form">
            <?= $form->field($model,'startFinishTime')->widget(
                DatePicker::className(),
                [
                    'name' => 'startFinishTime',
                    'value' => Date('Y-m-d'),
                    'type' => DatePicker::TYPE_COMPONENT_PREPEND,
//                    'removeButton' => false,
                    'pluginOptions' => [
                        'autoclose' => true,
                        'format' => 'yyyy-mm-dd'
                    ]
                ]
            )->label(Yii::t('app','Finish time'))?>
        </div>
        <div class="form-group filter-form">
            <?= $form->field($model,'endFinishTime')->widget(
                DatePicker::className(),
                [
                    'name' => 'endFinishTime',
                    'value' => Date('Y-m-d'),
                    'type' => DatePicker::TYPE_COMPONENT_PREPEND,
//                    'removeButton' => false,
                    'pluginOptions' => [
                        'autoclose' => true,
                        'format' => 'yyyy-mm-dd'
                    ]
                ]
            )->label('~')?>
        </div>
    </div>

    <div class="form-inline">
        <div class="form-group filter-form" >
            <?= $form->field($model,'projectId')->label(Yii::t('app','Project Id'))->input('text',['class' =>'form-control','id' => 'projectId'])?>
        </div>
        <div class="form-group filter-form">
            <?= $form->field($model,'workType')->dropDownList(
            /** @var array $workType */
                $workType,
                ['prompt'=>'Select Option']
            )->label(Yii::t('app','Work type'))?>
        </div>
    </div>

    <div class="form-inline">
        <div class="form-group filter-form">
            <?= $form->field($model,'identifyPlace')->dropDownList(
                $identify,
                ['prompt'=>'Select Option']
            )->label(Yii::t('app','Identify place'))?>
        </div>


        <div class="form-group filter-form">
            <label class="control-label" for="workType"><?= Yii::t('app','Branch')?></label>
            <select class="form-control" name="" id="branch">
                <option value="">Select Option</option>
                <?php
                     foreach ($dataWorkList as $rows) {
                ?>
                    <option value=""><?= $rows['level_name 2'] ?></option>
                <?php } ?>
            </select>
        </div>
       <!-- <div class="form-group filter-form">
            <?php /* $test = $row['level_name 2']  */?>
            <?/*= $form->field($model,'level_name_2')->dropDownList(
                $row['level_name 2'],
                ['prompt'=>'Select Option']
            )->label(Yii::t('app','Branch'))*/?>
        </div>-->

    </div>


</div>

<?php ActiveForm::end() ?>
<?php Modal::end(); ?>



<?php $this->registerCssFile('@web/css/work-list.css') ?>
<?php $this->registerJsFile('@web/js/work-list.js',['depends' => [\yii\web\JqueryAsset::className()]]) ?>